apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rmp
spec:
  workspaces:
  - name: pipeline-ws1
  tasks:
    - name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-ws1
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/obenlieger/RegattaMeldung.git
        - name: revision
          value: master      
    - name: buildah
      workspaces:
        - name: source
          workspace: pipeline-ws1
      taskRef:
        name: buildah
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: tuxone/regattameldung:1.13
        - name: DOCKERFILE
          value: ./RegattaMeldung/Dockerfile
        - name: CONTEXT
          value: ./RegattaMeldung
