apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  genrateName: buildah- 
  labels: 
    tekton.dev/task: buildah
spec:
  taskRef:
    name: buildah
  params: 
    - name: IMAGE
      value: tuxone/regattameldung:1.18
    - name: DOCKERFILE
      value: ./RegattaMeldung/Dockerfile
    - name: CONTEXT
      value: ./RegattaMeldung
  workspaces: 
    - name: source
      persistentVolumeClaim:
        claimName: rm-pvc